### ISSUE TITLE
OpenShift Free Small Gear - Cassandra 3

### ISSUE THREAD

**Issue by ravilution** [rajatchopra/openshift-origin-cartridge-cassandra#2]
Hi,

I am trying to install Cassandra 3 in OpenShift Small Gear. Tried all possible. I get some or the other issues. The last issue I got was JMX port already in use. Can you add to this cartridge the Cassandra 3 version?

**Comment by MassimoCappellano** [comment]
In file _openshift-origin-cartridge-cassandra/versions/3.1/conf/cassandra-env.sh_, I've commented this, I seem to remember for that problem.

```
  #JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT"
  #JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.rmi.port=$JMX_PORT"
  #JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.ssl=false"
  #JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=true"
  #JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.password.file=/etc/cassandra/jmxremote.password"
```
