### ISSUE TITLE
How can I access that cassandra from outside world

### ISSUE THREAD

**Issue by ravilution** [rajatchopra/openshift-origin-cartridge-cassandra#3]
I have installed the Cassandra 3.0 using this cartridge. How can I access it from internet. I am able to access it inside after I ssh. But I want to access it from outside world.

**Comment by ravilution** [comment]
I used `rhc port-forward -a`

**Comment by BransonGitomeh** [comment]
@ravilution how did you use the the forwarding the ports? i cant even even figure how to acess it even inside with ssh. can you post some instruction snippets? :-) please?
