### ISSUE TITLE
Cassandra 3.6

### ISSUE THREAD

**Issue by ravilution** [rajatchopra/openshift-origin-cartridge-cassandra#4]
Can we have [Cassandra 3.6](https://github.com/apache/cassandra/blob/trunk/CHANGES.txt) version added. I badly want to use the new features. [LIKE](https://issues.apache.org/jira/browse/CASSANDRA-11067) feature to be more particular.

**Comment by ravilution** [comment]
Hi Guys,
Any help will be highly appreciated. Thanks.

**Comment by MassimoCappellano** [comment]
Hi Ravi,

I've done for now upgrade to cassandra version 3.4 and for now is in my repository:

I've tested and seems ok. To installa for example on an application `cassandra2store`:

```
rhc app-create cassandra2store -t nodejs-0.10 -g medium

rhc cartridge add https://raw.githubusercontent.com/MassimoCappellano/openshift-origin-cartridge-cassandra/master/metadata/manifest.yml --app cassandra2store

```

If it's ok, I will do a pull request.
Massimo

**Comment by ravilution** [comment]
Hi Massimo,

Thanks a lot. It works great. Just like old times.

Am not an openshift expert. But I got a suggestion. I [use this](https://github.com/icflorescu/openshift-cartridge-nodejs) cartridge to install latest node into openshift. The cartridge automatically installs the latest version. Can we do something like that of our cartridge. I feel that will be a one time solution to version issues. Just a thought.

Ravi

**Comment by MassimoCappellano** [comment]
Hi Ravi,
perfect, thaks for suggestion on nodejs cartridge, now I will use that. Thanks
Massimo

**Comment by BransonGitomeh** [comment]
hey guys, i added the catridge to a small app, with node js but the env ports dont return anything ie

``` javascript

var express = require('express');
var app = express();

app.get('/', function(req, res) {
    res.send({
        cassandra_host: process.env.OPENSHIFT_CASSANDRA_HOST,
        cassandra_port: process.env.OPENSHIFT_CASSANDRA_PORT,
        cassandra_log_dir: process.env.OPENSHIFT_CASSANDRA_LOG_DIR,
        cassandra_native_transport_port: process.env.OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT
    })
});

const port = process.env.OPENSHIFT_NODEJS_PORT || 4000
const ip = process.env.OPENSHIFT_NODEJS_IP || "localhost"

app.listen(port, ip, 511, function(err) {
    console.log('listening on *:' + port);
});
```

only returns

``` javascript
{"cassandra_native_transport_port":"19042"}
```

everything else just gets ignored. what am i not doing correctly?... or is there anything on github using this catridge? @MassimoCappellano how do you do it ? :-D

**Comment by MassimoCappellano** [comment]
Hi Branie,

In effect there is some error in the README about the names of the valiables exported. I didn't notice before. 

Once connected with ssh to my instance, I have done a script like your, `test.js`

```
var myEnv = {
        cassandra_host: process.env.OPENSHIFT_CASSANDRA_HOST,
        cassandra_port: process.env.OPENSHIFT_CASSANDRA_PORT,
        cassandra_log_dir: process.env.OPENSHIFT_CASSANDRA_LOG_DIR,
        cassandra_native_transport_port: process.env.OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT
    };

console.log(myEnv);
```

the result was:

```
[cassandra2store-simplethings.rhcloud.com tmp]\> node test.js
{ cassandra_host: undefined,
  cassandra_port: undefined,
  cassandra_log_dir: undefined,
  cassandra_native_transport_port: '19042' }
[cassandra2store-simplethings.rhcloud.com tmp]\>
```

in effect doing:

```
[cassandra2store-simplethings.rhcloud.com 56fe75567628e1f4b6000143]\> env | grep CASSANDRA
OPENSHIFT_CASSANDRA_DB_HOST=127.13.104.2
OPENSHIFT_CASSANDRA_USERNAME=
OPENSHIFT_CASSANDRA_PASSWORD=
OPENSHIFT_CASSANDRA_URL=
OPENSHIFT_CASSANDRA_DB_PORT=19160
OPENSHIFT_CASSANDRA_DB_LOG_DIR=/var/lib/openshift/56fe75567628e1f4b6000143/cassandra//cassandra/log/
OPENSHIFT_CASSANDRA_DIR=/var/lib/openshift/56fe75567628e1f4b6000143/cassandra/
OPENSHIFT_CASSANDRA_IDENT=rc:cassandra:3.4:0.0.2
OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT=19042
[cassandra2store-simplethings.rhcloud.com 56fe75567628e1f4b6000143]\>
```

in effect the CASSANDRA variable for HOST, LOG_DIR are different

In this way, is OK, I think:

```
var myEnv = {
        cassandra_host: process.env.OPENSHIFT_CASSANDRA_DB_HOST,
        cassandra_port: process.env.OPENSHIFT_CASSANDRA_DB_PORT,
        cassandra_log_dir: process.env.OPENSHIFT_CASSANDRA_DB_LOG_DIR,
        cassandra_native_transport_port: process.env.OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT
    };

console.log(myEnv);
```

The meccanism to export the variable in te cartridge was for me a bit complicate. From the original cartridge I've added only the `OPENSHIFT_CASSANDRA_NATIVE_TRANSPORT_PORT`. I hope this was helpfull. I will correct the README and ask Rajat to do the merge.

Hi Massimo

**Comment by BransonGitomeh** [comment]
Hi @MassimoCappellano 

ALL that worked awesome :-D i'm so happy. yea that should be in the read-me definitely . Thanks for the quick response so far.
